name: easypaisa
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  confetti: ^0.7.0
  intl: ^0.19.0
  mobile_scanner: ^5.1.0
  google_fonts: ^6.1.0
  audioplayers: ^6.0.0
  video_player: ^2.8.6
  shared_preferences: ^2.2.2
  http: ^1.1.0
  firebase_core: ^2.24.2
  firebase_database: ^10.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/EP2_logo.jpg"
  min_sdk_android: 21
  adaptive_icon_background: "#000000"

flutter_native_splash:
  color: "#000000"
  background_image: assets/Start_anim.jpg
  android_gravity: fill
  fullscreen: true

  android_12:
    color: "#000000"
    icon_background_color: "#000000"
    image: assets/Start_anim.jpg
    fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/EP2_logo.jpg
    - assets/Start_anim.jpg
    - assets/frames/
    - assets/confetti_frames/
    - assets/home_bg.jpg
    - assets/send_menu_bg.png
    - assets/settings_bg.jpg
    - assets/ep_cl.webp
    - assets/wallet_ik.png
    - assets/sounds/
    - assets/splash.mp4
    - assets/re_ep.jpg
    - assets/reciept_2.jpg
    - assets/qr_icons.jpg
